### PR TITLE
[minor] Add files whitelist to package.json (SP-516)

### PR DESCRIPTION
**Pull request by jheanly**
We're currently not limiting the files that are packaged with the `ahm-config` repo, so when we publish a new version of that to `npm` we are also shipping a bunch of dev tools and other junk that doesn't need to be there.

This PR introduces the use of the `files` property in `package.json` to whitelist files that should be packaged.

See here (https://blog.npmjs.org/post/165769683050/publishing-what-you-mean-to-publish) for an explanation of the `files` feature.

Jira: https://medibankdigital.atlassian.net/browse/SP-516

### CODE REVIEW

**Review by nicgordon — APPROVED** [review]
Love this! For others reviewing it is worth noting that:

> npm will always include these files in a package:
> 
> package.json
> README and its variants like README.md
> CHANGELOG and its variants
> LICENSE and the alternative spelling LICENCE

**Comment by camjc** [comment]
Does this mean we can remove any npmignore files we find along the way?

**Comment by jheanly** [comment]
@camjc _"Does this mean we can remove any npmignore files we find along the way?"_ - that's my understanding

**Comment by nicgordon** [comment]
Well we'd need to replace `.npmignore` files with this `files` property in the `package.json` of every repo that has one, but yes.

**Review by leonardoanalista — APPROVED** [review]
nice!

**Pull request merged**
